### ISSUE TITLE
Is it possible to run this on macos 10.15.7?

### ISSUE THREAD

**Issue by kcky436348hdfg6** [tommy19970714/PowerfulVirtualBackground#1]
Hello! Thank you for your app! But unfortunately I can't start it on my mac because it requires macos 11 minimum. Is there any way to run it on my macos 10.15.7? thanks

**Comment by tommy19970714** [comment]
This project was created by SwiftUI, so unfortunately it requires macOS 11 minimum.
If you recreate it without SwiftUI, I think it will work on your macOS.
As for the virtual camera plugin, it works on macOS 10.15.7 if you re-build it.

**Comment by FengMu1995** [comment]
@tommy19970714  Hi，I wondered if the macos app can be used in ios
